In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

# Load historical data for the asset you want to trade

data = yf.download("0003.HK", start="2023-06-01", end="2023-10-27")

data["Close"].tail()

[*********************100%***********************]  1 of 1 completed

Date
2023-10-06    62.049999
2023-10-09    62.000000
2023-10-10    62.200001
2023-10-11    62.799999
2023-10-12    63.200001
Name: Close, dtype: float64

In [5]:
# Calculate the moving average of the asset's price over a certain period of time
data["ma"] = data["Close"].rolling(window=20).mean()
data.tail()

,Open,High,Low,Close,Adj Close,Volume,ma,trend
Date,,,,,,,,
2023-10-06,61.700001,62.200001,61.549999,62.049999,62.049999,15669740,60.3300,1
2023-10-09,62.400002,62.650002,61.700001,62.000000,62.000000,8766123,60.5650,1
2023-10-10,62.000000,62.799999,61.750000,62.200001,62.200001,17611242,60.7925,1
2023-10-11,62.950001,63.150002,62.650002,62.799999,62.799999,22109361,61.0350,1
2023-10-12,63.599998,63.700001,63.049999,63.200001,63.200001,18785947,61.2450,1

In [6]:
# Create a new column that shows whether the asset's price is trending upward or downward
data["trend"] = np.where(data["Close"] > data["ma"], 1, -1)
data["trend"].tail()

Date
2023-10-06    1
2023-10-09    1
2023-10-10    1
2023-10-11    1
2023-10-12    1
Name: trend, dtype: int32

In [7]:
# Use the trend column to make buy or sell decisions
#for i in range(len(data)):

print("Trend Following Trading Strategy")
Buy_time=1.0
data2=data.loc[data.trend==Buy_time]
print("Long")
print(data2["Close"])

print("")
print("")
Sell_time= -1.0
data2=data.loc[data.trend==Sell_time]
print("Short")
print(data2["Close"])

Trend Following Trading Strategy
Long
Date
2023-06-29    60.849998
2023-06-30    61.000000
2023-07-03    61.950001
2023-07-04    62.250000
2023-07-05    61.650002
2023-07-06    61.000000
2023-07-10    60.950001
2023-07-12    61.400002
2023-07-13    62.150002
2023-07-14    62.799999
2023-07-18    62.950001
2023-07-19    63.250000
2023-07-20    63.799999
2023-07-21    64.300003
2023-07-24    63.700001
2023-07-25    64.500000
2023-07-26    64.650002
2023-07-27    64.949997
2023-07-28    64.800003
2023-07-31    65.199997
2023-08-01    66.300003
2023-08-02    64.199997
2023-08-04    63.849998
2023-08-07    63.950001
2023-08-08    64.000000
2023-09-13    59.000000
2023-09-14    59.750000
2023-09-15    60.849998
2023-09-18    60.750000
2023-09-19    60.700001
2023-09-20    61.099998
2023-09-21    60.799999
2023-09-22    61.400002
2023-09-25    61.049999
2023-09-26    60.400002
2023-09-27    60.849998
2023-09-28    60.599998
2023-09-29    61.700001
2023-10-03    60.900002
2023-10-04    60.849998
2023-10-05    60.950001
2023-10-06    62.049999
2023-10-09    62.000000
2023-10-10    62.200001
2023-10-11    62.799999
2023-10-12    63.200001
Name: Close, dtype: float64


Short
Date
2023-06-01    57.349998
2023-06-02    58.200001
2023-06-05    59.150002
2023-06-06    59.049999
2023-06-07    59.650002
2023-06-08    59.950001
2023-06-09    60.000000
2023-06-12    60.000000
2023-06-13    59.900002
2023-06-14    60.049999
2023-06-15    60.049999
2023-06-16    61.000000
2023-06-19    61.400002
2023-06-20    61.500000
2023-06-21    61.299999
2023-06-23    59.750000
2023-06-26    59.599998
2023-06-27    60.500000
2023-06-28    60.849998
2023-07-07    60.650002
2023-07-11    60.750000
2023-08-03    62.900002
2023-08-09    63.849998
2023-08-10    62.599998
2023-08-11    62.599998
2023-08-14    62.349998
2023-08-15    61.200001
2023-08-16    59.950001
2023-08-17    59.299999
2023-08-18    58.650002
2023-08-21    58.500000
2023-08-22    58.549999
2023-08-23    58.400002
2023-08-24    58.849998
2023-08-25    58.400002
2023-08-28    58.750000
2023-08-29    58.500000
2023-08-30    59.349998
2023-08-31    58.849998
2023-09-04    58.750000
2023-09-05    57.650002
2023-09-06    57.750000
2023-09-07    57.299999
2023-09-11    57.650002
2023-09-12    57.950001
Name: Close, dtype: float64